"""
Prometheus metrics registry for the incident-reporter service.

Metrics exposed
───────────────
Alert routing (Phase 4)
  alerts_sent_total          Counter   — alerts that reached a notification channel
  alerts_suppressed_total    Counter   — alerts blocked by rate limiter
  pagerduty_api_errors_total Counter   — HTTP errors calling the PagerDuty Events API

A Prometheus HTTP server is started on METRICS_PORT (default 9101) so that
Prometheus can scrape /metrics independently from the Kafka consumer loop.
"""

from __future__ import annotations

import logging
import os
import threading

from prometheus_client import Counter, Histogram, start_http_server

logger = logging.getLogger(__name__)

# ── metric definitions ────────────────────────────────────────────────────────

ALERTS_SENT = Counter(
    "alerts_sent_total",
    "Alerts successfully delivered to a notification channel",
    ["severity", "channel"],  # channel: slack | pagerduty
)

ALERTS_SUPPRESSED = Counter(
    "alerts_suppressed_total",
    "Alerts blocked before delivery (rate-limit or digest queue)",
    ["service", "reason"],  # reason: rate_limited | cooldown | storm_active
)

PAGERDUTY_API_ERRORS = Counter(
    "pagerduty_api_errors_total",
    "HTTP errors encountered when calling the PagerDuty Events API v2",
    ["action"],  # action: trigger | resolve
)

REPORT_PIPELINE_LATENCY = Histogram(
    "report_pipeline_latency_seconds",
    "End-to-end latency for the IncidentReportPipeline (enrich → scrub → AI → store)",
    ["service"],
    buckets=(0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 30.0, 60.0),
)

REPORTS_GENERATED = Counter(
    "reports_generated_total",
    "Incident reports generated by the pipeline",
    ["service", "ai_generated"],  # ai_generated: true | false
)

# ── server lifecycle ──────────────────────────────────────────────────────────

_server_started = False
_lock = threading.Lock()


def start_metrics_server(port: int | None = None) -> None:
    """Start the Prometheus HTTP server (idempotent)."""
    global _server_started
    with _lock:
        if _server_started:
            return
        port = port or int(os.getenv("METRICS_PORT", "9101"))
        start_http_server(port)
        _server_started = True
        logger.info("Prometheus metrics server started on port %d", port)
