---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-headless
  namespace: {{ include "log-monitor.namespace" . }}
  labels:
    {{- include "log-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/name: opensearch
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "log-monitor.selectorLabels" (dict "component" "opensearch" "root" .) | nindent 4 }}
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: {{ include "log-monitor.namespace" . }}
  labels:
    {{- include "log-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/name: opensearch
spec:
  selector:
    {{- include "log-monitor.selectorLabels" (dict "component" "opensearch" "root" .) | nindent 4 }}
  ports:
    - name: http
      port: 9200
      targetPort: 9200
